# Generated by Django 5.1.3 on 2024-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="posts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=100)),
                ("author_image", models.ImageField(upload_to="posts_author/")),
                ("author_positions", models.CharField(max_length=100)),
            ],
        ),
    ]
