# Generated by Django 5.1.3 on 2024-11-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mooseapp", "0003_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
