# Generated by Django 5.1.3 on 2024-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mooseapp", "0004_remove_post_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
