# Generated by Django 5.1.3 on 2024-11-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mooseapp", "0006_category_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
    ]
